version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sql_chatapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=admin # Ajuste para o valor real que você deseja usar
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql-data:
  mongo-data:
